//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { RouteParameterDTO } from './RouteParameterDTO';

export class RoutePartDTO {
	public name: string;
	public parameter: RouteParameterDTO;
	public childRoutPart: RoutePartDTO;

	// constructor(name: string, parameter: RouteParameterDTO, childRoutPart?: RoutePartDTO) {
	// 	this.name = name;
	// 	this.parameter = parameter;
	// 	this.childRoutPart = childRoutPart;
	// }
}
