//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class RouteParameterDTO {
	public isMandatory: boolean;
	public parameterType: number;

	constructor(isMandatory: boolean = true, parameterType: number = 0) {
		this.isMandatory = isMandatory;
		this.parameterType = parameterType;
	}
}
