//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { AdmObjectDTO } from './AdmObjectDTO';

export class AdmObjectFieldDTO
{
	public id: any;
	public rusName: string;
	public text: string;
	public objectText: string;
	public objectFieldText: string;
	public description: string;
	public adm_ObjectId: any;
	public dataTypeLength: string;
	public defaultValue: string;
	public id_Adm_Object_FK: string;
	public id_Adm_ObjectField_FK: string;
	public object: AdmObjectDTO;
	public orderNumber: number;
	public isLog: boolean;
	public wherePredicate: string;
	public Clone() : AdmObjectFieldDTO
	{
		return null;
	}
}
