//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { AdmObjectFieldDTO } from './AdmObjectFieldDTO';

export class AdmObjectDTO
{
	public id: any;
	public name: string;
	public rusName: string;
	public text: string;
	public description: string;
	public adm_ObjectType: string;
	public adm_ScalarDataType: string;
	public loc: string;
	public queueNumber: number;
	public isTransferable: number;
	public fields: AdmObjectFieldDTO[];
}
