//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class CompareOperatorDTO
{
	public id: string;
	public name: string;
	public shortName: string;
	public description: string;
	public isUnary: boolean;
	public availableForTypes: string[];
}
