//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ConditionCompareDTO } from './ConditionCompareDTO';

export class CompareLogicDTO
{
	public id: any;
	public parentId: any;
	public boolOperator: string;
	public children: CompareLogicDTO[];
	public conditionCompare: ConditionCompareDTO;
	public message: string;
	public type: string;
}
