//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CompareOperatorDTO } from './CompareOperatorDTO';
import { ConditionCompareOperandDTO } from './ConditionCompareOperandDTO';

export class ConditionCompareDTO {
    public id: any;
    public compareOperator: CompareOperatorDTO;
    public ignoreCase: boolean;
    public conditionCompareOperandFirst: ConditionCompareOperandDTO;
    public conditionCompareOperandSecond: ConditionCompareOperandDTO;
}
