//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { AdmObjectDTO } from './AdmObjectDTO';

export class ConditionObjectDTO
{
	public id: any;
	public adm_Object: AdmObjectDTO;
	public rusName: string;
}
