//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class ConditionParameterDTO
{
	public id: any;
	public name: string;
	public description: string;
	public type: string;
	public adm_ScalarDataTypeId: string;
	public systemType: string;
	public defaultValue: string;
	public id_TemplateKeyValue: any;
	public orderNum: number;
	public isRequired: boolean;
}
