//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { TemplateDTO } from './TemplateDTO';

export class MassOperationParamDTO
{
	public id: any;
	public code: string;
	public template: TemplateDTO;
	public templateFieldKey: string;
	public templateFieldValue: string;
}
