//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ConditionObjectDTO } from './ConditionObjectDTO';
import { AdmObjectFieldDTO } from './AdmObjectFieldDTO';
import { TemplateDTO } from './TemplateDTO';
import { CompareLogicDTO } from './CompareLogicDTO';

export class TemplateFieldDTO
{
	public id: any;
	public colNumber: number;
	public name: string;
	public note: string;
	public conditionObject: ConditionObjectDTO;
	public adm_ObjectField: AdmObjectFieldDTO;
	public hidden: boolean;
	public isRemovedFromResultSet: boolean;
	public orderType: string;
	public type: string;
	public systemType: string;
	public id_TemplateKeyValue: any;
	public templateKeyValue: TemplateDTO;
	public id_DataSourceTemplateField: any;
	public sP_LookupAlgId: string;
	public lookupAlgParameter: string;
	public templateKeyValueLogic: CompareLogicDTO;
}
