//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { MenuItemBaseDTO } from "./MenuItemBaseDTO";


export class DisplayedMenuItemDTO extends MenuItemBaseDTO {
    public id: any;
    public displayedChildren: DisplayedMenuItemDTO[];
}
