//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class DynamicElementConfigurationDTO
{
	public id: any;
	public elementName: string;
	public modelBasedSettings: { [key:string]: string };
	public valuePath: string;
	public children: DynamicElementConfigurationDTO[];
}
