//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class MenuItemBaseDTO
{
	public name: string;
	public orderIndex: number;
	public externalUrl: string;
	public internalPageId: any;
	public parametersObjectJson: string;
}
