//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { TemplateFieldDTO } from './TemplateFieldDTO';

export class TemplateDTO
{
	public id: any;
	public isUser: boolean;
	public name: string;
	public id_TemplateUpload: any;
	public uploadTemplate: TemplateDTO;
	public xpos: number;
	public ypos: number;
	public procedureName: string;
	public topRows: number;
	public code: string;
	public codeSQL: string;
	public isCache: boolean;
	public templateFields: TemplateFieldDTO[];
	public conditionObjects: any[];
	public conditionParameters: any[];
	public filtering: any;
	public validation: any;
	public admObject: any;
	public id_DataSource: any;
	public id_TemplateType: string;
	public procedureManager: string;
	public massOperations: any[];
	public massOperationsNoSelection: any[];
	public isSubquery: boolean;
	public isLogChanges: boolean;
	public catalogTemplateForParameters: TemplateDTO[];
	public catalogTemplateForFields: TemplateDTO[];
	public uploadTemplateForTemplates: TemplateDTO[];
	public massOperationParamTemplateForTemplates: TemplateDTO[];
	public subQueryTemplateForTemplates: TemplateDTO[];
	public dataSourceForUserTemplates: TemplateDTO[];
	public tableReferences: any[];
}
