//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { TemplateDTO } from './TemplateDTO';

export class TemplateFieldDTO
{
	public id: any;
	public colNumber: number;
	public name: string;
	public note: string;
	public conditionObject: any;
	public admObjectField: any;
	public hidden: boolean;
	public isRemovedFromResultSet: boolean;
	public orderType: string;
	public type: string;
	public systemType: string;
	public id_TemplateKeyValue: any;
	public templateKeyValue: TemplateDTO;
	public id_DataSourceTemplateField: any;
	public id_LookupAlg: boolean;
	public lookupAlgParameter: string;
	public templateKeyValueLogic: any;
}
